#!/usr/bin/env node
// Static-site assembler for roughcut.com.au (RC-13.1; plan: .planning/HOME-AND-SITE-PLAN.md §4-5).
//
// Node built-ins only. No framework, no dependencies.
//
//   npm run site:build   ->  site/dist/   (plain HTML/CSS/JS, uploaded by hand to Hostinger)
//
// What it does:
//   1. Reads app/globals.css and extracts VERBATIM: the @theme block (emitted as :root custom
//      properties), every @keyframes, the prefers-reduced-motion block and the print block.
//      The site never types a token value, so it cannot drift from the app.
//   2. Prepends those to the hand-written site/src/site.css  ->  site/dist/site.css
//   3. Inlines site/src/partials/<name>.html into pages where `<!-- @include name -->` appears,
//      substitutes {{KEY}} from site/site.config.json, and writes site/src/pages/*.html -> site/dist/
//   4. Copies every other file under site/src (reveal.js, .htaccess, img/, og/ ...) to site/dist/
//
// tests/site-tokens.test.ts imports the functions below and proves the parity.

import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, statSync, copyFileSync, existsSync } from 'node:fs';
import { join, dirname, relative, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const PATHS = {
  appCss: join(ROOT, 'app', 'globals.css'),
  src: join(ROOT, 'site', 'src'),
  dist: join(ROOT, 'site', 'dist'),
  config: join(ROOT, 'site', 'site.config.json'),
};

// ── CSS block extraction ──────────────────────────────────────────────────────

/** Index of the `{` that opens the block whose prelude starts at `start`, or -1. */
function openBraceAfter(css, start) {
  const i = css.indexOf('{', start);
  return i;
}

/** Index just past the `}` that closes the block opened at `open` (brace-balanced). */
function closeBraceFrom(css, open) {
  let depth = 0;
  for (let i = open; i < css.length; i++) {
    const ch = css[i];
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) return i + 1;
    }
  }
  throw new Error(`Unbalanced braces in CSS after index ${open}`);
}

/**
 * Every top-level block whose prelude matches `preludeRe` (anchored at a line start),
 * returned verbatim: `{ prelude, body, text }` where text = prelude + body incl. braces.
 */
export function extractBlocks(css, preludeRe) {
  const out = [];
  const re = new RegExp(`^${preludeRe.source}\\s*(?=\\{)`, 'gm');
  let m;
  while ((m = re.exec(css))) {
    const open = openBraceAfter(css, m.index + m[0].length - 1);
    const end = closeBraceFrom(css, open);
    out.push({ prelude: m[0].trimEnd(), body: css.slice(open, end), text: css.slice(m.index, end) });
    re.lastIndex = end;
  }
  return out;
}

export function extractTheme(css) {
  const blocks = extractBlocks(css, /@theme/);
  if (blocks.length !== 1) throw new Error(`Expected exactly one @theme block in app/globals.css, found ${blocks.length}`);
  return blocks[0];
}

export function extractKeyframes(css) {
  return extractBlocks(css, /@keyframes\s+[\w-]+/);
}

export function extractReducedMotion(css) {
  const blocks = extractBlocks(css, /@media\s*\(prefers-reduced-motion:\s*reduce\)/);
  if (blocks.length !== 1) throw new Error(`Expected one prefers-reduced-motion block, found ${blocks.length}`);
  return blocks[0];
}

export function extractPrint(css) {
  const blocks = extractBlocks(css, /@media\s+print/);
  if (blocks.length !== 1) throw new Error(`Expected one @media print block, found ${blocks.length}`);
  return blocks[0];
}

/** `--name: value;` declarations inside a block body (comments stripped), as a Map. */
export function parseCustomProps(body) {
  const noComments = body.replace(/\/\*[\s\S]*?\*\//g, '');
  const map = new Map();
  const re = /(--[\w-]+)\s*:\s*([^;]+);/g;
  let m;
  while ((m = re.exec(noComments))) map.set(m[1], m[2].trim());
  return map;
}

/** The generated top of site.css: tokens as :root, keyframes, then the hand-written layer, then media blocks. */
export function buildSiteCss(appCss, handWritten) {
  const theme = extractTheme(appCss);
  const keyframes = extractKeyframes(appCss);
  const reduced = extractReducedMotion(appCss);
  const print = extractPrint(appCss);

  const root = ':root ' + theme.body; // `@theme {` -> `:root {`, body verbatim

  return [
    '/* GENERATED by scripts/build-site.mjs from app/globals.css. Do not edit. */',
    '/* ── Design tokens (app @theme, verbatim) ── */',
    root,
    '',
    '/* ── Keyframes (app, verbatim) ── */',
    ...keyframes.map((k) => k.text),
    '',
    '/* END GENERATED: tokens + keyframes. Hand-written layer follows (site/src/site.css). */',
    handWritten.trimEnd(),
    '',
    '/* GENERATED: reduced-motion and print policy (app, verbatim). Do not edit. */',
    reduced.text,
    '',
    print.text,
    '',
  ].join('\n');
}

// ── HTML assembly ─────────────────────────────────────────────────────────────

export function assemblePage(html, partials, config) {
  let out = html.replace(/<!--\s*@include\s+([\w-]+)\s*-->/g, (_, name) => {
    if (!(name in partials)) throw new Error(`Unknown partial "${name}"`);
    return partials[name].trimEnd();
  });
  out = out.replace(/\{\{\s*([A-Z_]+)\s*\}\}/g, (_, key) => {
    if (!(key in config)) throw new Error(`Unknown config key {{${key}}}`);
    return String(config[key]);
  });
  return out;
}

function walk(dir) {
  const files = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) files.push(...walk(p));
    else files.push(p);
  }
  return files;
}

// ── Build ─────────────────────────────────────────────────────────────────────

export function build({ outDir = PATHS.dist } = {}) {
  const appCss = readFileSync(PATHS.appCss, 'utf8');
  const handWritten = readFileSync(join(PATHS.src, 'site.css'), 'utf8');
  // {{YEAR}} (footer copyright) is computed at build time, like the app's `new Date().getFullYear()`.
  const config = { ...JSON.parse(readFileSync(PATHS.config, 'utf8')), YEAR: String(new Date().getFullYear()) };

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const written = [];

  // 1-2. CSS
  const siteCss = buildSiteCss(appCss, handWritten);
  writeFileSync(join(outDir, 'site.css'), siteCss);
  written.push('site.css');

  // 3. Pages
  const partialsDir = join(PATHS.src, 'partials');
  const partials = {};
  for (const f of readdirSync(partialsDir)) {
    if (f.endsWith('.html')) partials[f.replace(/\.html$/, '')] = readFileSync(join(partialsDir, f), 'utf8');
  }
  const pagesDir = join(PATHS.src, 'pages');
  for (const f of readdirSync(pagesDir)) {
    if (!f.endsWith('.html')) continue;
    const html = assemblePage(readFileSync(join(pagesDir, f), 'utf8'), partials, config);
    writeFileSync(join(outDir, f), html);
    written.push(f);
  }

  // 4. Everything else under src is copied as-is
  const skip = new Set([join(PATHS.src, 'site.css'), partialsDir, pagesDir]);
  for (const abs of walk(PATHS.src)) {
    if (skip.has(abs) || abs.startsWith(partialsDir + sep) || abs.startsWith(pagesDir + sep)) continue;
    const rel = relative(PATHS.src, abs);
    const dest = join(outDir, rel);
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(abs, dest);
    written.push(rel.split(sep).join('/'));
  }

  return { outDir, written, siteCss };
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  const { outDir, written } = build();
  if (!existsSync(join(outDir, 'index.html'))) throw new Error('index.html was not produced');
  console.log(`site:build -> ${relative(ROOT, outDir)}/  (${written.length} files)`);
  for (const f of written) console.log('  ' + f);
}
